name: MinecraftServer
version: @version@
main: peace.minecraftserver.MinecraftServer
depends:
  - Vault
  - TitleAPI
  - VexView
commands:
  main:
    description: open main
    usage: /main <shop>|<insure>|<function>|<achieve>
  getMoney:
    description: This is a money demo command.
    usage: /<getMoney>

  insureshow:
    description: show player insure state
    usage: /<insure>

  shop:
    description: open shop
    usage: /shop <auction>|<buy>|<lottery>
  insure:
    description: open insure gui
    usage: /insure <message>|<buy>|
  achievement:
    description: open achievement gui
    usage: /achieve <message>|<buy>|
  function:
    description: open function gui
    usage: /function <message>|<buy>|
  playtime:
    description: get your playtime

  money:
  show:
  cheat:
  #攻击特效指令
  attack:
  #落地特效
  round:
  #跟随特效
  follow:
permissions:
  playtime.*:
    description: get your playtime
    children:
      playtime.use: true
      playtime.use.other: true
      playtime.top10: true
      playtime.settime: true
      playtime.help: true
  playtime.use:
    description: 查看自己的在线时间
    default: true
  playtime.use.other:
    description: 查看其他人的在线时间
    default: true
  playtime.top10:
    description: 查看在线时间前10的玩家
    default: true
  playtime.settime:
    description: 设置玩家的在线时间
    default: true
  playtime.help:
    description: 查看在线时间前10的玩家
    default: true
