name: MinecraftServer
version: @version@
main: peace.minecraftserver.MinecraftServer
depends:
  - Vault
  - TitleAPI
  - VexView
commands:
  main:
    description: open main
    usage: /main <shop>|<insure>|<function>|<achieve>
  getMoney:
    description: This is a money demo command.
    usage: /<getMoney>

  insureshow:
    description: show player insure state
    usage: /<insure>

  shop:
    description: open shop
    usage: /shop <auction>|<buy>|<lottery>
  insure:
    description: open insure gui
    usage: /insure <message>|<buy>|
  achievement:
    description: open achievement gui
    usage: /achieve <message>|<buy>|
  function:
    description: open function gui
    usage: /function <message>|<buy>|
  playtime:
    description: get your playtime
  money:
  show:
  cheat:
  #攻击特效指令
  attack:
  #落地特效
  round:
  #跟随特效
  follow:

