name: MinecraftServer
version: @version@
main: peace.minecraftserver.MinecraftServer
depends:
  - Vault
  - TitleAPI
  - VexView
commands:
  main:
    description: open main
    usage: /main <shop>|<insure>|<function>|<achieve>
  getMoney:
    description: Used for show money
    usage:
  shop:
    description: open shop
    usage: shop <auction>|<buy>|<lottery>
  insure:
    description: open
    usage: /insure <message>|<buy>|
  playtime:
  money:
  show:
  cheat: